spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/zakupki
spring.datasource.username=postgres
spring.datasource.password=Qeadws1234
server.port=8080
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=admin
spring.security.user.password=admin
logging.level.org.springframework.security.web.session=DEBUG
logging.level.org.springframework.security.authentication=DEBUG
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dimondim25@gmail.com
spring.mail.password=yhrqfjfeyhbsevfz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework=DEBUG